version: '3.0'

services:
  caddy:
    image: caddy
    container_name: caddy
    networks:
      - default
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './volumes/caddy:/data/caddy'
      - './config/caddy/Caddyfile:/etc/caddy/Caddyfile'

  rss-bridge:
    image: rssbridge/rss-bridge:latest
    container_name: rss-bridge
    expose:
      - 80
    volumes:
      - './config/rssbridge/whitelist.txt:/app/whitelist.txt'

  freshrss-app:
    image: freshrss/freshrss:latest
    container_name: freshrss-app
    hostname: freshrss-app
    restart: unless-stopped
    depends_on:
      - freshrss-db
    volumes:
      - './volumes/freshrss/data:/var/www/FreshRSS/data'
      - './volumes/freshrss/ext:/var/www/FreshRSS/extensions'
    environment:
      CRON_MIN: '4,24,44'
      TZ: America/Los_Angeles
    expose:
      - 8080

  freshrss-db:
    image: postgres:12-alpine
    container_name: freshrss-db
    hostname: freshrss-db
    restart: unless-stopped
    volumes:
      - './volumes/freshrss-db:/var/lib/postgresql/data'
    expose:
      - 5432
    environment:
      POSTGRES_USER: freshrss
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: rss-db
  
  ##
  # Backup
  #
  borg:
    image: dannyben/borg-client:latest
    container_name: borg
    volumes:
      - './volumes:/volumes'
      - './backups:/borg-repo'
    environment:
      BORG_REPO: '/borg-repo'
      BORG_PASSPHRASE: ${BORG_PASSWORD}
