version: '3.0'

services:
  caddy:
    image: caddy
    container_name: caddy
    networks:
      - default
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './volumes/caddy:/data/caddy'
      - './config/caddy/Caddyfile:/etc/caddy/Caddyfile'

  rss-bridge:
    image: rssbridge/rss-bridge:latest
    container_name: rss-bridge
    expose:
      - 80
    volumes:
      - './config/rssbridge/whitelist.txt:/app/whitelist.txt'
      - './config/rssbridge/config.ini.php:/app/config.default.ini.php'
  
  freshrss-app:
    image: freshrss/freshrss:latest
    container_name: freshrss-app
    hostname: freshrss-app
    restart: unless-stopped
    depends_on:
      - freshrss-db
    volumes:
      - './volumes/freshrss/data:/var/www/FreshRSS/data'
      - './volumes/freshrss/ext:/var/www/FreshRSS/extensions'
    environment:
      CRON_MIN: '4,24,44'
      TZ: America/Los_Angeles
    expose:
      - 8080

  freshrss-db:
    image: postgres:12-alpine
    container_name: freshrss-db
    hostname: freshrss-db
    restart: unless-stopped
    volumes:
      - './volumes/freshrss-db:/var/lib/postgresql/data'
    expose:
      - 5432
    environment:
      POSTGRES_USER: freshrss
      POSTGRES_PASSWORD: ${RSS_POSTGRES_PASSWORD}
      POSTGRES_DB: rss-db

  wallabag-app:
    image: wallabag/wallabag
    container_name: wallabag-app
    hostname: wallabag-app
    environment:
      - POSTGRES_USER=wallabag
      - POSTGRES_PASSWORD=${BKMK_POSTGRES_PASSWORD}
      - SYMFONY__ENV__DATABASE_DRIVER=pdo_pgsql
      - SYMFONY__ENV__DATABASE_HOST=wallabag-db
      - SYMFONY__ENV__DATABASE_PORT=5432
      - SYMFONY__ENV__DATABASE_CHARSET=utf8
      - SYMFONY__ENV__SECRET=${WALLABAG_SECRET}
      - SYMFONY__ENV__DATABASE_NAME=wallabag
      - SYMFONY__ENV__DATABASE_USER=wallabag
      - SYMFONY__ENV__DATABASE_PASSWORD=${BKMK_POSTGRES_PASSWORD}
      - POPULATE_DATABASE=True
      - SYMFONY__ENV__MAILER_USER=~
      - SYMFONY__ENV__MAILER_PASSWORD=~
      - SYMFONY__ENV__DOMAIN_NAME=https://wallabag.patladjan.com
      - TRUSTED_PROXIES=caddy
    expose:
      - 80
    volumes:
      - './volumes/wallabag/images:/var/www/wallabag/web/assets/images'
      - './volumes/wallabag/data:/var/www/wallabag/data'
    depends_on:
      - wallabag-db
      - wallabag-redis

  wallabag-db:
    image: postgres:12-alpine
    container_name: wallabag-db
    hostname: wallabag-db
    restart: unless-stopped
    volumes:
      - './volumes/wallabag-db:/var/lib/postgresql/data'
    expose:
      - 5432
    environment:
      POSTGRES_USER: wallabag
      POSTGRES_PASSWORD: ${BKMK_POSTGRES_PASSWORD}
      POSTGRES_DB: wallabag-db
  

  wallabag-redis:
    image: redis:alpine
    container_name: wallabag-redis
    volumes:
      - "./volumes/wallabag-redis:/dat"

  ##
  # Backup
  #
  borg:
    image: dannyben/borg-client:latest
    container_name: borg
    volumes:
      - './volumes:/volumes'
      - './backups:/borg-repo'
    environment:
      BORG_REPO: '/borg-repo'
      BORG_PASSPHRASE: ${BORG_PASSWORD}
